import { invoke } from './api.js';
import { discoveryCard, installedRow, emptyState, detail, recipeView } from './render.js';
const $ = id => document.getElementById(id);
const state = { view: 'discover', query: '', category: '', offset: 0, limit: 12, entries: [], apps: [], visibleApps: [], total: 0 };
let request = 0, searchTimer, toastTimer, selectedApp, pendingApp, activeRecipe, refreshError;
const message = error => error?.message || String(error);
function toast(text) { clearTimeout(toastTimer); $('toast').textContent = text; $('toast').hidden = false; toastTimer = setTimeout(() => { $('toast').hidden = true; }, 6000); }
function loadState(loading) { $('content').setAttribute('aria-busy', String(loading)); }
async function refreshApps() { try { state.apps = await invoke('list_apps'); refreshError = null; $('app-count').textContent = state.apps.length; } catch (error) { refreshError = error; $('app-count').textContent = '–'; } }
async function render() {
  const token = ++request; $('pagination').hidden = true;
  if (state.view === 'apps') {
    loadState(false); if (refreshError) { showError(refreshError); return; }
    const query = state.query.toLowerCase(); state.visibleApps = state.apps.filter(app => `${app.display_name} ${app.launch_url}`.toLowerCase().includes(query));
    $('results-count').textContent = `${state.visibleApps.length} ${state.visibleApps.length === 1 ? 'app' : 'apps'}`;
    $('content').innerHTML = state.visibleApps.length ? `<div class="installed-list">${state.visibleApps.map(installedRow).join('')}</div>` : emptyState(state.query ? 'No matching apps' : 'Your apps belong here.', state.query ? 'Try another name or address.' : 'Install a reviewed recipe or connect an app you already run.', state.query ? 'clear' : 'discover', state.query ? 'Clear search' : 'Discover apps'); return;
  }
  loadState(true); $('content').innerHTML = '<div class="loading" role="status">Finding your next app…</div>'; $('results-count').textContent = '';
  try {
    const page = await invoke('search_catalog', { query: state.query, category: state.category, offset: state.offset, limit: state.limit }); if (token !== request) return;
    state.entries = page.entries; state.total = page.total; const select = $('category'); if (select.options.length === 1) page.categories.forEach(category => select.add(new Option(category, category))); select.value = state.category;
    $('results-count').textContent = `${page.total.toLocaleString()} ${page.total === 1 ? 'project' : 'projects'}`; $('catalog-note').textContent = `${page.catalog_total.toLocaleString()} projects to discover · Reviewed installs are clearly marked`;
    $('content').innerHTML = page.entries.length ? `<div class="app-grid">${page.entries.map(discoveryCard).join('')}</div>` : emptyState('Nothing here just yet.', 'Try a different search or category. You can also connect an app that isn’t in this collection.', 'clear', 'Clear filters', 'search');
    $('pagination').hidden = page.total <= state.limit; $('page-label').textContent = `${state.offset + 1}–${Math.min(state.offset + state.limit, page.total)} of ${page.total.toLocaleString()} projects`; $('previous').disabled = state.offset === 0; $('next').disabled = state.offset + state.limit >= page.total;
  } catch (error) { if (token === request) showError(error); } finally { if (token === request) loadState(false); }
}
function showError(error) { $('content').innerHTML = emptyState('We couldn’t load your workspace.', message(error), 'retry', 'Try again', 'circle-alert'); }
function navigate(view) {
  clearTimeout(searchTimer); state.view = view; state.query = ''; state.category = ''; state.offset = 0; $('search').value = ''; $('category').value = ''; const discover = view === 'discover';
  for (const [id, active] of [['nav-discover', discover], ['nav-apps', !discover]]) { $(id).classList.toggle('selected', active); if (active) $(id).setAttribute('aria-current', 'page'); else $(id).removeAttribute('aria-current'); }
  $('breadcrumb').textContent = discover ? 'Discover' : 'My Apps'; $('eyebrow').textContent = discover ? 'THE SELF-HOSTED COLLECTION' : 'YOUR PERSONAL WORKSPACE'; $('page-title').textContent = discover ? 'Good software. Your space.' : 'Right where you left them.';
  $('intro').textContent = discover ? 'Find your next self-hosted app. Install reviewed recipes or connect the ones you already run.' : 'Start, stop, open, and inspect apps from one calm workspace.'; $('results-title').textContent = discover ? 'Explore the collection' : 'Your apps'; $('search').placeholder = discover ? 'Search apps, ideas, and tools…' : 'Search your apps…'; $('discovery-note').hidden = !discover; $('category-wrap').hidden = !discover; $('catalog-note').textContent = discover ? 'Independent software. A little closer to home.' : 'Your app registry is saved on this computer.'; render();
}
function openConnect(name = '') { $('connect-form').reset(); $('connect-name').value = name; $('connect-error').textContent = ''; $('connect-dialog').showModal(); (name ? $('connect-url') : $('connect-name')).focus(); }
async function reviewInstall(recipeId) {
  $('install-content').innerHTML = '<div class="loading" role="status">Checking Docker and recipe…</div>'; $('install-error').textContent = ''; $('install-confirm').disabled = true; $('install-dialog').showModal();
  try { const [recipe, report] = await Promise.all([invoke('recipe_details', { id: recipeId }), invoke('doctor')]); activeRecipe = recipe; $('install-title').textContent = `Review ${recipe.display_name} installation`; $('install-confirm').textContent = `Install ${recipe.display_name}`; $('install-confirm').disabled = !report.ready; $('install-content').innerHTML = recipeView(recipe, report); if (!report.ready) $('install-error').textContent = 'Start Docker Desktop and make sure Docker Compose is available, then reopen this review.'; }
  catch (error) { $('install-content').innerHTML = ''; $('install-error').textContent = message(error); }
}
async function runAppAction(button, command, app, success) {
  const old = button.innerHTML; button.disabled = true; button.textContent = command === 'start_app' ? 'Starting…' : 'Stopping…'; const target = $(`app-error-${state.visibleApps.indexOf(app)}`); if (target) target.textContent = '';
  try { await invoke(command, { id: app.id }); await refreshApps(); await render(); toast(success); } catch (error) { if (target) target.textContent = message(error); } finally { if (button.isConnected) { button.disabled = false; button.innerHTML = old; } }
}
$('nav-discover').onclick = () => navigate('discover'); $('nav-apps').onclick = async () => { await refreshApps(); navigate('apps'); }; document.querySelector('.brand').onclick = event => { event.preventDefault(); navigate('discover'); }; $('connect-top').onclick = $('connect-note').onclick = () => openConnect(); $('about').onclick = () => $('about-dialog').showModal();
$('search').addEventListener('input', () => { clearTimeout(searchTimer); ++request; state.query = $('search').value; state.offset = 0; searchTimer = setTimeout(render, 180); }); $('category').onchange = () => { clearTimeout(searchTimer); state.category = $('category').value; state.offset = 0; render(); }; $('previous').onclick = () => { state.offset = Math.max(0, state.offset - state.limit); render(); }; $('next').onclick = () => { state.offset += state.limit; render(); };
document.addEventListener('keydown', event => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k' && !document.querySelector('dialog[open]')) { event.preventDefault(); $('search').focus(); } }); document.addEventListener('error', event => { if (event.target.matches?.('.app-avatar img')) event.target.remove(); }, true);
document.addEventListener('click', async event => {
  const button = event.target.closest('button'); if (!button) return; if (button.dataset.close) { $(button.dataset.close).close(); return; }
  if (button.dataset.detail !== undefined) { selectedApp = state.entries[Number(button.dataset.detail)]; $('detail-content').innerHTML = detail(selectedApp); $('detail-dialog').showModal(); $('detail-primary').onclick = () => { $('detail-dialog').close(); selectedApp.capability === 'verified_install' ? reviewInstall(selectedApp.recipe_id) : openConnect(selectedApp.name); }; $('open-source').onclick = async () => { try { await invoke('open_project', { url: selectedApp.source_url }); } catch (error) { $('detail-error').textContent = message(error); } }; return; }
  if (button.dataset.action === 'connect') openConnect(); if (button.dataset.action === 'discover') navigate('discover'); if (button.dataset.action === 'clear') { $('search').value = ''; $('category').value = ''; state.query = ''; state.category = ''; state.offset = 0; render(); } if (button.dataset.action === 'retry') { await refreshApps(); render(); }
  const keyed = ['open','shortcut','start','stop','logs','remove','uninstall'].find(key => button.dataset[key] !== undefined); if (!keyed) return; const app = state.visibleApps[Number(button.dataset[keyed])];
  if (keyed === 'remove') { pendingApp = app; $('remove-description').textContent = `${app.display_name} will be removed from My Apps.`; $('remove-error').textContent = ''; $('remove-dialog').showModal(); return; }
  if (keyed === 'uninstall') { pendingApp = app; $('delete-data').checked = false; $('uninstall-confirm').textContent = 'Uninstall, keep data'; $('uninstall-description').textContent = `${app.display_name} and its container will be removed. Its data is preserved by default.`; $('uninstall-error').textContent = ''; $('uninstall-dialog').showModal(); return; }
  if (keyed === 'logs') { $('logs-title').textContent = `${app.display_name} logs`; $('logs-content').textContent = 'Loading…'; $('logs-error').textContent = ''; $('logs-dialog').showModal(); try { $('logs-content').textContent = await invoke('app_logs', { id: app.id }) || 'No recent output.'; } catch (error) { $('logs-content').textContent = ''; $('logs-error').textContent = message(error); } return; }
  if (keyed === 'start' || keyed === 'stop') { await runAppAction(button, keyed === 'start' ? 'start_app' : 'stop_app', app, `${app.display_name} ${keyed === 'start' ? 'started' : 'stopped'}.`); return; }
  const old = button.innerHTML; button.disabled = true; button.textContent = keyed === 'open' ? 'Opening…' : 'Creating…'; try { await invoke(keyed === 'open' ? 'open_app' : 'create_shortcut', { id: app.id }); toast(keyed === 'open' ? `${app.display_name} opened.` : `Shortcut created for ${app.display_name}.`); } catch (error) { $(`app-error-${state.visibleApps.indexOf(app)}`).textContent = message(error); } finally { button.disabled = false; button.innerHTML = old; }
});
$('connect-form').onsubmit = async event => {
  event.preventDefault(); const name = $('connect-name').value.trim(), rawUrl = $('connect-url').value.trim();
  try { const url = new URL(rawUrl); if (!/^https?:\/\//i.test(rawUrl) || !['http:', 'https:'].includes(url.protocol) || !url.hostname || url.username || url.password || /\s/.test(rawUrl)) throw new Error('Enter an http:// or https:// address without embedded credentials.'); if (!name) throw new Error('Enter a name for this connection.'); $('connect-submit').disabled = true; $('connect-submit').textContent = 'Saving…'; $('connect-error').textContent = ''; await invoke('add_app', { name, url: rawUrl }); $('connect-dialog').close(); await refreshApps(); navigate('apps'); toast(`${name} added to My Apps.`); } catch (error) { $('connect-error').textContent = message(error); } finally { $('connect-submit').disabled = false; $('connect-submit').textContent = 'Add to My Apps →'; }
};
$('install-confirm').onclick = async () => { $('install-confirm').disabled = true; $('install-confirm').textContent = 'Installing…'; $('install-error').textContent = ''; try { await invoke('install_app', { recipeId: activeRecipe.id }); $('install-dialog').close(); await refreshApps(); navigate('apps'); toast(`${activeRecipe.display_name} installed and ready.`); } catch (error) { $('install-error').textContent = message(error); $('install-confirm').disabled = false; $('install-confirm').textContent = `Install ${activeRecipe.display_name}`; } };
$('remove-confirm').onclick = async () => { $('remove-confirm').disabled = true; try { await invoke('remove_app_cmd', { id: pendingApp.id }); $('remove-dialog').close(); await refreshApps(); render(); toast('Connection removed. App data is unchanged.'); } catch (error) { $('remove-error').textContent = message(error); } finally { $('remove-confirm').disabled = false; } };
$('delete-data').onchange = () => { $('uninstall-confirm').textContent = $('delete-data').checked ? 'Uninstall and delete data' : 'Uninstall, keep data'; };
$('uninstall-confirm').onclick = async () => { const deleteData = $('delete-data').checked; if (deleteData && !window.confirm('Permanently delete this app’s managed data? This cannot be undone.')) return; $('uninstall-confirm').disabled = true; try { await invoke('uninstall_app', { id: pendingApp.id, deleteData }); $('uninstall-dialog').close(); await refreshApps(); render(); toast(deleteData ? 'App and managed data deleted.' : 'App uninstalled. Managed data was preserved.'); } catch (error) { $('uninstall-error').textContent = message(error); } finally { $('uninstall-confirm').disabled = false; } };
await refreshApps(); render();
