//! Generate the CapRover import report.
//!
//! Reads a JSON object of `{app id: normalized definition}` on stdin, runs the
//! real adapter over each one, and writes Markdown to stdout.
//! `scripts/caprover_import_report.py` supplies that object from the
//! checksum-pinned upstream archive.
//!
//! Nothing here installs, writes into the repository, or promotes an app.
use local_store::importers::{caprover, ImportOutcome};
use std::collections::BTreeMap;
use std::io::{self, Read};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut input = String::new();
    io::stdin()
        .take(32 * 1024 * 1024 + 1)
        .read_to_string(&mut input)?;
    if input.len() > 32 * 1024 * 1024 {
        return Err("input exceeds limit".into());
    }
    let mut arguments = std::env::args().skip(1);
    let revision = arguments.next().unwrap_or_else(|| "unknown".into());

    let apps: serde_json::Value = serde_json::from_str(&input)?;
    let apps = apps.as_object().ok_or("expected an apps object")?;

    let mut outcomes = Vec::new();
    let mut unreadable = Vec::new();
    for (id, definition) in apps {
        match caprover::import(id, &definition.to_string()) {
            Ok(outcome) => outcomes.push(outcome),
            Err(reason) => unreadable.push(reason),
        }
    }

    let importable: Vec<&ImportOutcome> = outcomes.iter().filter(|o| o.is_importable()).collect();
    // Count each app once per distinct feature, so one app with three
    // placeholders does not look like three blocked apps.
    let mut blocked_by: BTreeMap<(&str, &str), Vec<&str>> = BTreeMap::new();
    for outcome in outcomes.iter().filter(|o| !o.is_importable()) {
        let mut seen: Vec<(&str, &str)> = outcome
            .limitations
            .iter()
            .map(|limit| (limit.category(), limit.feature()))
            .collect();
        seen.sort_unstable();
        seen.dedup();
        for key in seen {
            blocked_by.entry(key).or_default().push(&outcome.id);
        }
    }

    println!("# CapRover import report");
    println!();
    println!(
        "Generated by `scripts/caprover_import_report.py` from the checksum-pinned\n\
         CapRover one-click catalogue at revision `{revision}`, which is Apache-2.0.\n\
         Read-only: nothing here is installed, no upstream expression is evaluated,\n\
         and no app becomes a reviewed recipe by appearing in this table."
    );
    println!();
    println!("## Summary");
    println!();
    println!("| Result | Apps |");
    println!("| --- | --- |");
    println!("| Definitions read | {} |", outcomes.len());
    println!(
        "| Fully expressible as a plan today | {} |",
        importable.len()
    );
    println!(
        "| Blocked by at least one limitation | {} |",
        outcomes.len() - importable.len()
    );
    if !unreadable.is_empty() {
        println!("| Unreadable definitions | {} |", unreadable.len());
    }
    println!();
    println!(
        "Expressible is not verified. Every app in the second table still needs a\n\
         real install, health, restart, preserved-data reinstall and deletion run\n\
         before it could be offered to anyone."
    );
    println!();

    println!("## What blocks the rest");
    println!();
    println!("| Category | Feature | Apps | Examples |");
    println!("| --- | --- | --- | --- |");
    let mut rows: Vec<_> = blocked_by.iter().collect();
    rows.sort_by(|a, b| b.1.len().cmp(&a.1.len()).then(a.0.cmp(b.0)));
    for ((category, feature), apps) in rows {
        let examples: Vec<&str> = apps.iter().take(3).copied().collect();
        println!(
            "| {category} | `{feature}` | {} | {} |",
            apps.len(),
            examples.join(", ")
        );
    }
    println!();
    println!(
        "*Refused* means the setting is deliberately not expressible: accepting it\n\
         would give a container privileges the reviewed recipes refuse, or would\n\
         publish an address the plan model does not allow. Those apps need an\n\
         upstream change or a different source, not more of this importer."
    );
    println!();

    println!("## Apps that map cleanly today");
    println!();
    if importable.is_empty() {
        println!("None.");
    } else {
        println!("| App | Services | Container port | Secrets | Asks for |");
        println!("| --- | --- | --- | --- | --- |");
        for outcome in &importable {
            let template = outcome
                .template
                .as_ref()
                .expect("importable outcomes carry a template");
            let plan = &template.plan;
            let port = plan
                .published()
                .map(|(_, port)| port.container.to_string())
                .unwrap_or_else(|| "-".into());
            // The questions a person would be asked, so a candidate can be
            // judged on whether they are answerable rather than only counted.
            let asks: Vec<String> = template
                .fields
                .iter()
                .map(|field| {
                    let mark = if field.required { "*" } else { "" };
                    format!("{}{mark}", field.key)
                })
                .collect();
            println!(
                "| {} | {} | {port} | {} | {} |",
                outcome.id,
                plan.services.len(),
                template.secrets.len(),
                if asks.is_empty() {
                    "-".to_owned()
                } else {
                    asks.join(", ")
                }
            );
        }
    }

    if !unreadable.is_empty() {
        println!();
        println!("## Unreadable definitions");
        println!();
        for reason in &unreadable {
            println!("- {reason}");
        }
    }
    Ok(())
}
