//! Generate the Runtipi import report.
//!
//! Reads a directory of `<app-id>/docker-compose.json` files, maps each one
//! with the read-only importer, and writes a Markdown report to stdout.
//! `scripts/runtipi_import_report.py` supplies that directory from the pinned
//! upstream archive already cached for the catalog build.
//!
//! Nothing here installs, writes into the repository, or promotes an app.
use local_store::importers::{runtipi, ImportOutcome};
use std::collections::BTreeMap;

fn main() {
    let mut arguments = std::env::args().skip(1);
    let Some(directory) = arguments.next() else {
        eprintln!("usage: runtipi_report <directory of <app-id>/docker-compose.json>");
        std::process::exit(2);
    };
    let revision = arguments.next().unwrap_or_else(|| "unknown".into());

    let mut definitions: Vec<(String, String, Option<String>)> = Vec::new();
    let entries = std::fs::read_dir(&directory).unwrap_or_else(|error| {
        eprintln!("cannot read {directory}: {error}");
        std::process::exit(1);
    });
    for entry in entries.flatten() {
        let path = entry.path().join("docker-compose.json");
        if let Ok(text) = std::fs::read_to_string(&path) {
            let id = entry.file_name().to_string_lossy().into_owned();
            let config = std::fs::read_to_string(entry.path().join("config.json")).ok();
            definitions.push((id, text, config));
        }
    }
    definitions.sort_by(|a, b| a.0.cmp(&b.0));

    let mut outcomes = Vec::new();
    let mut unreadable = Vec::new();
    for (id, text, config) in &definitions {
        match runtipi::import(id, text, config.as_deref()) {
            Ok(outcome) => outcomes.push(outcome),
            Err(reason) => unreadable.push(reason),
        }
    }

    let importable: Vec<&ImportOutcome> = outcomes.iter().filter(|o| o.is_importable()).collect();
    // Count each app once per distinct feature, so a single app with three
    // placeholders does not look like three blocked apps.
    let mut blocked_by: BTreeMap<(&str, &str), Vec<&str>> = BTreeMap::new();
    for outcome in outcomes.iter().filter(|o| !o.is_importable()) {
        let mut seen: Vec<(&str, &str)> = outcome
            .limitations
            .iter()
            .map(|limit| (limit.category(), limit.feature()))
            .collect();
        seen.sort_unstable();
        seen.dedup();
        for key in seen {
            blocked_by.entry(key).or_default().push(&outcome.id);
        }
    }

    println!("# Runtipi import report");
    println!();
    println!(
        "Generated by `scripts/runtipi_import_report.py` from the pinned Runtipi\n\
         app store at revision `{revision}`. Read-only: nothing here is installed,\n\
         and no app becomes a reviewed recipe by appearing in this table."
    );
    println!();
    println!("## Summary");
    println!();
    println!("| Result | Apps |");
    println!("| --- | --- |");
    println!("| Definitions read | {} |", outcomes.len());
    println!(
        "| Fully expressible as a plan today | {} |",
        importable.len()
    );
    println!(
        "| Blocked by at least one limitation | {} |",
        outcomes.len() - importable.len()
    );
    if !unreadable.is_empty() {
        println!("| Unreadable definitions | {} |", unreadable.len());
    }
    println!();
    println!(
        "A blocked app is not a rejected app. Every row below is a named gap, and\n\
         the ones marked *not modelled* or *needs input* are the work queue for the\n\
         remaining phase 2 features."
    );
    println!();

    println!("## What blocks the rest");
    println!();
    println!("| Category | Feature | Apps | Examples |");
    println!("| --- | --- | --- | --- |");
    let mut rows: Vec<_> = blocked_by.iter().collect();
    rows.sort_by(|a, b| b.1.len().cmp(&a.1.len()).then(a.0.cmp(b.0)));
    for ((category, feature), apps) in rows {
        let examples: Vec<&str> = apps.iter().take(3).copied().collect();
        println!(
            "| {category} | `{feature}` | {} | {} |",
            apps.len(),
            examples.join(", ")
        );
    }
    println!();
    println!(
        "*Refused* means the setting is deliberately not expressible: accepting it\n\
         would give a container privileges the reviewed recipes refuse. Those apps\n\
         need an upstream change or a different source, not more of this importer."
    );
    println!();

    println!("## Apps that map cleanly today");
    println!();
    if importable.is_empty() {
        println!("None.");
    } else {
        println!("| App | Services | Published port | Setup fields | Secrets |");
        println!("| --- | --- | --- | --- | --- |");
        for outcome in &importable {
            let template = outcome
                .template
                .as_ref()
                .expect("importable outcomes carry a template");
            let plan = &template.plan;
            let port = plan
                .published()
                .map(|(_, port)| port.host.to_string())
                .unwrap_or_else(|| "-".into());
            println!(
                "| {} | {} | {port} | {} | {} |",
                outcome.id,
                plan.services.len(),
                template.fields.len(),
                template.secrets.len()
            );
        }
    }
    println!();
    println!(
        "Mapping cleanly is not verification. Each of these still needs a real\n\
         install, health, restart, preserved-data reinstall and deletion run before\n\
         it could be offered as an install."
    );

    if !unreadable.is_empty() {
        println!();
        println!("## Unreadable definitions");
        println!();
        for reason in &unreadable {
            println!("- {reason}");
        }
    }
}
