"""Reproduce source-format counts; NOT an importer or installability verdict.

Reads only a checksum-verified cached archive. No downloads, extraction or app
execution. Regenerate with python scripts/audit-caprover-source.py.
"""
import collections
import hashlib
import json
from pathlib import Path
import zipfile
import yaml

ROOT = Path(__file__).resolve().parents[1]


def audit(archive, expected_digest):
    if hashlib.sha256(archive.read_bytes()).hexdigest() != expected_digest:
        raise ValueError("CapRover archive checksum differs from pinned audit source")
    counts = collections.Counter()
    keys = collections.Counter()
    errors = []
    with zipfile.ZipFile(archive) as bundle:
        names = sorted(name for name in bundle.namelist()
                       if "/public/v4/apps/" in name and name.endswith(".yml"))
        for name in names:
            if bundle.getinfo(name).file_size > 1024 * 1024:
                raise ValueError("oversized app definition")
            counts["Definitions"] += 1
            try:
                app = yaml.safe_load(bundle.read(name))
                services = app.get("services", {})
                variables = app.get("caproverOneClickApp", {}).get("variables", [])
                counts["Services"] += len(services)
                counts["Setup variables"] += len(variables)
                if variables:
                    counts["Apps declaring setup variables"] += 1
                patterns = [v for v in variables if v.get("validRegex")]
                counts["Variables with validation patterns"] += len(patterns)
                if patterns:
                    counts["Apps with validation patterns"] += 1
                generated = [v for v in variables if "$$cap_gen_random_hex(" in str(v.get("defaultValue", ""))]
                counts["Generated hexadecimal variables"] += len(generated)
                if generated:
                    counts["Apps declaring hexadecimal secrets"] += 1
                endpoints = 0
                for service in services.values():
                    keys.update(service.keys())
                    endpoints += int("containerHttpPort" in service.get("caproverExtra", {}))
                    if "$$" in str(service.get("image", "")):
                        counts["Images containing CapRover substitutions"] += 1
                counts[f"Apps with {endpoints if endpoints < 2 else 'multiple'} explicit HTTP port declarations"] += 1
            except (AttributeError, TypeError, yaml.YAMLError) as error:
                errors.append((Path(name).name, type(error).__name__))
    return counts, keys, errors


def main():
    source = json.loads((ROOT / "catalog/import-audit-sources.json").read_text())["caprover"]
    archive = ROOT / ".cache/catalog" / f"caprover-{source['revision']}.zip"
    if not archive.exists():
        raise SystemExit(f"Missing pinned archive: {archive}; this checker never downloads")
    counts, keys, errors = audit(archive, source["sha256"])
    lines = ["# CapRover source-format audit", "",
             f"Pinned revision: `{source['revision']}`. Archive SHA-256: `{source['sha256']}`.", "",
             "Generated by `python scripts/audit-caprover-source.py` using the existing PyYAML dependency.",
             "These are source-format counts, not numbers of importable or working apps.",
             "An absent explicit HTTP port may use a platform default; no endpoint is inferred here.", "",
             "| Measurement | Count |", "| --- | --- |"]
    lines.extend(f"| {name} | {count} |" for name, count in sorted(counts.items()))
    lines.extend(["", "## Service keys", "", "Counts are per service, not per app.", "",
                  "| Key | Services |", "| --- | --- |"])
    lines.extend(f"| `{name}` | {count} |" for name, count in keys.most_common())
    lines.extend(["", f"Parse errors: {len(errors)}.", ""])
    lines.extend(f"- {name}: {kind}" for name, kind in errors)
    (ROOT / "docs/caprover-source-audit.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps(dict(counts), sort_keys=True))
    if errors:
        raise SystemExit("Source parse errors recorded; do not treat audit as complete")


if __name__ == "__main__":
    main()
