#!/usr/bin/env python3
"""Build the V2 prototype's long-content stress fixtures from the real catalog.

Phase 15 must verify the layout against real content, not the prototype's short,
friendly fixture strings. This selects catalog entries deterministically:

  * the three longest descriptions,
  * the three longest names,
  * the widest and tallest icons by aspect ratio (three each),

de-duplicated in that order, and writes docs/design/v2/stress-fixtures.js.
Re-running it on the same catalog produces the same file.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "src" / "generated" / "catalog.json"
ASSETS = ROOT / "src"
OUT = ROOT / "docs" / "design" / "v2" / "stress-fixtures.js"


def aspect(icon: str) -> float | None:
    path = ASSETS / icon
    if not path.is_file():
        return None
    if path.suffix == ".svg":
        text = path.read_text(encoding="utf-8", errors="ignore")[:4000]
        box = re.search(r'viewBox="\s*[-\d.]+[\s,]+[-\d.]+[\s,]+([\d.]+)[\s,]+([\d.]+)', text)
        if box and float(box.group(2)):
            return float(box.group(1)) / float(box.group(2))
        size = re.search(r'width="([\d.]+)[^"]*"\s+height="([\d.]+)', text)
        return float(size.group(1)) / float(size.group(2)) if size else None
    with Image.open(path) as image:
        return image.width / image.height if image.height else None


def main() -> None:
    raw = json.loads(CATALOG.read_text(encoding="utf-8"))
    entries = raw if isinstance(raw, list) else next(v for v in raw.values() if isinstance(v, list))
    usable = [e for e in entries if e.get("icon") and e.get("description") and (ASSETS / e["icon"]).is_file()]
    for entry in usable:
        entry["_aspect"] = aspect(entry["icon"])
    with_aspect = [e for e in usable if e["_aspect"]]

    picks: list[dict] = []
    def take(sequence, count, reason):
        for entry in sequence:
            if count == 0:
                break
            if entry["id"] not in {p["id"] for p in picks}:
                entry["_reason"] = reason
                picks.append(entry)
                count -= 1

    take(sorted(usable, key=lambda e: (-len(e["description"]), e["id"])), 3, "longest description")
    take(sorted(usable, key=lambda e: (-len(e["name"]), e["id"])), 3, "longest name")
    take(sorted(with_aspect, key=lambda e: (-e["_aspect"], e["id"])), 3, "widest icon")
    take(sorted(with_aspect, key=lambda e: (e["_aspect"], e["id"])), 3, "tallest icon")

    catalog = []
    for e in picks:
        catalog.append({
            "id": e["id"],
            "name": e["name"],
            "category": e.get("category") or "Uncategorised",
            "description": e["description"],
            "icon": f"assets/logos/{Path(e['icon']).name}",
            "license": (e.get("licenses") or ["See project"])[0],
            "capability": "connect" if e.get("web_ui") else "explore",
            "action": "Connect" if e.get("web_ui") else "Explore project",
            "maintenance": "Tracked" if e.get("maintenance") == "tracked" else "Snapshot",
            "architectures": e.get("architectures") or [],
            "tags": (e.get("tags") or [])[:4],
            "source": "stress fixture",
            "source_url": e.get("source_url") or "",
            "stress_reason": f"{e['_reason']} (aspect {e['_aspect']:.2f})" if e.get("_aspect") else e["_reason"],
        })

    body = (
        "// Generated by scripts/build-v2-stress-fixtures.py from src/generated/catalog.json.\n"
        "// Loaded only with ?stress=1. Do not edit by hand; re-run the script, then\n"
        "// scripts/vendor-v2-prototype-logos.py to copy the logos beside the prototype.\n"
        f"export const stressCatalog = {json.dumps(catalog, indent=2, ensure_ascii=True)};\n"
    )
    OUT.write_text(body, encoding="utf-8", newline="\n")
    for item in catalog:
        print(f"{item['id']:34s} {item['stress_reason']}")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(catalog)} entries)")


if __name__ == "__main__":
    main()
