#!/usr/bin/env python3
"""Render the pinned catalog icon manifest as a deterministic review sheet."""

from collections import defaultdict
import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "src/generated/catalog.json"
MANIFEST = ROOT / "catalog/icons.json"
OUTPUT = ROOT / "docs/design/v2/icon-contact-sheet.html"
SOURCE_ORDER = (
    "umbrel-apps-gallery",
    "homarr-dashboard-icons",
    "coolify",
    "local-store-monogram",
)
SOURCE_LABELS = {
    "umbrel-apps-gallery": "Umbrel gallery",
    "homarr-dashboard-icons": "Homarr dashboard icons",
    "coolify": "Coolify catalog",
    "local-store-monogram": "Satin monograms",
}


def main():
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))["entries"]
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))["icons"]
    by_source = defaultdict(list)
    for entry in catalog:
        record = manifest[entry["id"]]
        by_source[record["source"]].append((entry, record))

    sections = []
    for source in SOURCE_ORDER:
        rows = sorted(by_source[source], key=lambda row: (row[0]["name"].casefold(), row[0]["id"]))
        cards = []
        for entry, record in rows:
            asset = "../../../src/" + record["path"]
            cards.append(
                '<article class="icon-card">'
                f'<div class="icon-stage"><img src="{html.escape(asset)}" alt="" loading="lazy"></div>'
                '<div class="icon-copy">'
                f'<strong title="{html.escape(entry["name"])}">{html.escape(entry["name"])}</strong>'
                f'<code title="{html.escape(entry["id"])}">{html.escape(entry["id"])}</code>'
                f'<span>{html.escape(record["format"].upper())} · {record["width"]:g}×{record["height"]:g}</span>'
                '</div></article>'
            )
        sections.append(
            '<section class="source-section">'
            '<div class="section-heading">'
            f'<h2>{html.escape(SOURCE_LABELS[source])}</h2><span>{len(rows):,} assets</span>'
            '</div><div class="icon-grid">' + "".join(cards) + '</div></section>'
        )

    counts = {source: len(by_source[source]) for source in SOURCE_ORDER}
    page = f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Local Store · Icon Contact Sheet</title>
  <link rel="stylesheet" href="icon-contact-sheet.css">
</head>
<body>
  <main>
    <header class="masthead">
      <div class="brand-lockup">
        <img src="assets/brand/mark-grain-approved.svg" alt="">
        <div><span>Local Store V2</span><strong>Icon contact sheet</strong></div>
      </div>
      <div class="status"><i></i> phase 5 audit</div>
    </header>
    <section class="intro">
      <div>
        <p class="eyebrow">Pinned, validated, complete</p>
        <h1>Every app has a face.</h1>
        <p class="lede">A human-review surface for {len(catalog):,} catalog icons. Artwork is shown uncropped at its native aspect ratio; generated fallbacks use the approved Satin Ember accent.</p>
      </div>
      <div class="metric primary"><strong>{len(catalog):,}</strong><span>resolved icons</span></div>
    </section>
    <section class="metrics" aria-label="Coverage summary">
      <div class="metric"><strong>100%</strong><span>catalog coverage</span></div>
      <div class="metric"><strong>{counts['umbrel-apps-gallery']}</strong><span>Umbrel imports</span></div>
      <div class="metric"><strong>{counts['homarr-dashboard-icons'] + counts['coolify']}</strong><span>other upstream</span></div>
      <div class="metric"><strong>{counts['local-store-monogram']}</strong><span>deterministic fallbacks</span></div>
    </section>
    {''.join(sections)}
  </main>
  <footer>Generated by <code>scripts/render-icon-contact-sheet.py</code> from the pinned provenance manifest.</footer>
</body>
</html>
'''
    OUTPUT.write_text(page, encoding="utf-8", newline="\n")
    print(f"Rendered {len(catalog)} icons to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
