#!/usr/bin/env python3
"""Copy every app logo the V2 prototype uses into docs/design/v2/assets/logos/.

The prototype used to load logos from src/assets/catalog, so it rendered correctly
only on branches carrying the full icon set. This script makes the design package
self-contained: it reads each referenced logo from a git ref (default
feat/catalog-icons, where "a validated icon for every catalogue entry" landed),
checks it against that ref's catalog/icons.json, writes it beside the prototype,
rewrites the references, and records provenance in assets/logos/README.md.

  python scripts/vendor-v2-prototype-logos.py [--ref feat/catalog-icons]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V2 = ROOT / "docs" / "design" / "v2"
OUT = V2 / "assets" / "logos"
FIXTURES = [V2 / "prototype-fixtures.js", V2 / "stress-fixtures.js"]
REFERENCE = re.compile(r'"(?:\.\./\.\./\.\./src/assets/catalog|assets/logos)/([^"/]+)"')


def git_blob(ref: str, path: str) -> bytes:
    return subprocess.run(["git", "cat-file", "blob", f"{ref}:{path}"], cwd=ROOT, check=True, capture_output=True).stdout


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ref", default="feat/catalog-icons")
    args = parser.parse_args()
    manifest = json.loads(git_blob(args.ref, "catalog/icons.json"))["icons"]
    by_file = {Path(entry["path"]).name: (catalog_id, entry) for catalog_id, entry in manifest.items()}
    commit = subprocess.run(["git", "rev-parse", "--short", args.ref], cwd=ROOT, check=True, capture_output=True, text=True).stdout.strip()

    files = sorted({name for fixture in FIXTURES for name in REFERENCE.findall(fixture.read_text(encoding="utf-8"))})
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for name in files:
        catalog_id, entry = by_file[name]
        data = git_blob(args.ref, f"src/{entry['path']}")
        digest = hashlib.sha256(data).hexdigest()
        if digest != entry["sha256"]:
            raise SystemExit(f"{name}: sha256 {digest} does not match the manifest at {args.ref}")
        (OUT / name).write_bytes(data)
        rows.append(f"| `{name}` | `{catalog_id}` | {entry['source']} | {entry.get('license') or 'see source'} | "
                    f"[{entry.get('repository') or 'source'}]({entry.get('url') or ''}) | `{digest[:16]}…` |")
    for fixture in FIXTURES:
        text = fixture.read_text(encoding="utf-8")
        fixture.write_text(REFERENCE.sub(lambda m: f'"assets/logos/{m.group(1)}"', text), encoding="utf-8", newline="\n")

    (OUT / "README.md").write_text(
        "# V2 prototype logos\n\n"
        "Every app logo the prototype and its stress fixtures show, copied here so the design\n"
        "package renders on any branch without the catalog icon set. Generated by\n"
        f"`scripts/vendor-v2-prototype-logos.py --ref {args.ref}` from commit `{commit}`; each\n"
        "file matches the SHA-256 recorded in that commit's `catalog/icons.json`.\n\n"
        "Logos remain the property of their projects. Source, licence, and notice\n"
        "requirements follow the catalog icon manifest and `THIRD_PARTY_NOTICES.md`.\n\n"
        "| File | Catalog ID | Source | Licence | Repository | SHA-256 |\n"
        "| --- | --- | --- | --- | --- | --- |\n" + "\n".join(rows) + "\n",
        encoding="utf-8", newline="\n")
    print(f"vendored {len(rows)} logos from {args.ref} ({commit}) into {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
